### ISSUE TITLE
Trying to use cy-spok with webpack as preprocessor.

### ISSUE THREAD

**Issue by mandotpro** [bahmutov/cy-spok#38]
Hey I'm trying to run cy-spok using https://github.com/cypress-io/cypress-webpack-preprocessor .. but got random errors which I cannot resolve so far.

`Error: Webpack CompLooked for and couldn't find the file at the following paths:resolve 'child_process' in 'fullpath/node_modules/@bahmutov/spok/dist'
`

then tried to do this (because of webpack 5, no provide polifill)

`module.exports = {
  resolve: {
    fallback: {
      child_process: false,
    },`

I'm getting next error

`Error: Webpack CompLooked for and couldn't find the file at the following paths:resolve 'util' in 'fullpath/node_modules/@bahmutov/spok/dist'
`

Thanks in advance if you can help with that one and provide some configuration related to webpack processor.

**Comment by bahmutov** [comment]
Webpack 5 stopped including the Node system modules by default. This is an error one would get

```
Module not found: Error: Can't resolve 'util' in '/Users/glebbahmutov/git/cypress-plugins-course/e-spok-redux-window/node_modules/spok/dist'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "util": require.resolve("util/") }'
	- install 'util'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "util": false }
```

Ughh, there is not good solution if you don't have access to webpack config
