### ISSUE TITLE
Problem installing cy-spok

### ISSUE THREAD

**Issue by robertosmed** [bahmutov/cy-spok#41]
Hello! I'm having trouble trying to install cy-spok on my project. Deletes the package-log.json file from the project and gave npm install again to the project and then used the command [npm install -D bahmutov / cy-spok] but unsuccessfully presented the following error message below:
npm ERR! code E404
npm ERR! 404 Object Not Found - GET https://skimdb.npmjs.com/registry/@bahmutov%2fspok - not_found
npm ERR! 404 
npm ERR! 404  '@bahmutov/spok@1.2.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

Can anybody help me?
Operating system: windows 10 32 bit

**Comment by bahmutov** [comment]
@robertosmed can you try again? I have switched this module to use the original `spok` instead of my fork

**Comment by bahmutov** [comment]
I think this is resolved
